version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - pwd
      - aws s3 cp index.hmtl error.html error.css index.css s3://$S3_BUCKET
      - aws s3 ls s3://$S3_BUCKET
