version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - aws s3 cp ./ s3://$S3_BUCKET/ --recursive  --exclude "*.yaml" --exclude "*.md" --exclude "*.json" --exclude ".DS_Store"
      - aws s3 ls s3://$S3_BUCKET
