version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - pwd
      - ls
      - mkdir www
      - mv index.html resume.css error.html error.css www
      - ls www
      - cd www
      - aws s3 mv ./www s3://$S3_BUCKET
