version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - pwd
      - ls
      - aws s3 cp ./ s3://$S3_BUCKET/ --recursive --include "*.html" --include "*.css"
      - aws s3 ls s3://$S3_BUCKET
