version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - pwd
      - ls
      - mv * ./www
      - aws s3 mv -r ./www s3://$S3_BUCKET/index.hmtl
