version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - zip -r pulumi.zip .
      - aws s3 cp pulumi.zip s3://$S3_BUCKET/pulumi.zip
