name: Deploy latest release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.BUCKET_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"

      - name: Upload to CodeBuild
        run: |
          aws codebuild start-build --project-name ${{ secrets.CODEBUILD_PROJECT_NAME }} --source-version ${{ github.sha }} --environment-variables-override name=BUCKET_NAME,value=${{ secrets.BUCKET_NAME }},name=DISTRIBUTION_ID,value=${{ secrets.DISTRIBUTION_ID }}

      - run: |
          "echo "Deployment completed successfully." >> GITHUB_STEP_SUMMARY
          "" >> GITHUB_STEP_SUMMARY
          "echo https://richardcraddock.me" >> GITHUB_STEP_SUMMARY
